# Tutorial about np.linspace() and np.arange()

https://realpython.com/np-linspace-numpy/

In [1]:
import numpy as np
import timeit

With np.linspace()

In [2]:
# all parameters will be introduce one by one
# to summarize, the default values are
np.linspace(1.1,
         2.3,
         num=50,
         endpoint=True,
         retstep=False,
         dtype=None,
         axis=0
         )

array([1.1       , 1.1244898 , 1.14897959, 1.17346939, 1.19795918,
       1.22244898, 1.24693878, 1.27142857, 1.29591837, 1.32040816,
       1.34489796, 1.36938776, 1.39387755, 1.41836735, 1.44285714,
       1.46734694, 1.49183673, 1.51632653, 1.54081633, 1.56530612,
       1.58979592, 1.61428571, 1.63877551, 1.66326531, 1.6877551 ,
       1.7122449 , 1.73673469, 1.76122449, 1.78571429, 1.81020408,
       1.83469388, 1.85918367, 1.88367347, 1.90816327, 1.93265306,
       1.95714286, 1.98163265, 2.00612245, 2.03061224, 2.05510204,
       2.07959184, 2.10408163, 2.12857143, 2.15306122, 2.17755102,
       2.20204082, 2.22653061, 2.25102041, 2.2755102 , 2.3       ])

In [3]:
# equaly distanced, a vector space, or linear space
# closed range: the end of the range 10 is included in the array
# two required parameters: start and stop; by default 50 values
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [4]:
# set the number of values with num
np.linspace(1, 10, num = 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
# set the number of values you want as the third parameter
np.linspace(-10, 10, 25)

array([-10.        ,  -9.16666667,  -8.33333333,  -7.5       ,
        -6.66666667,  -5.83333333,  -5.        ,  -4.16666667,
        -3.33333333,  -2.5       ,  -1.66666667,  -0.83333333,
         0.        ,   0.83333333,   1.66666667,   2.5       ,
         3.33333333,   4.16666667,   5.        ,   5.83333333,
         6.66666667,   7.5       ,   8.33333333,   9.16666667,
        10.        ])

With Python's range

In [6]:
# the last value is not included, and they are integers not floats
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
# to create non integer values, use list comprehension
[float(i) for i in range(11)]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [8]:
[i-0.5 for i in range(11)]

[-0.5, 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5]

In [9]:
[i/10 for i in range(11)]

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [10]:
# to get the same values as np.linspace(-10, 10, 25)
np.linspace(-10, 10, 25)

array([-10.        ,  -9.16666667,  -8.33333333,  -7.5       ,
        -6.66666667,  -5.83333333,  -5.        ,  -4.16666667,
        -3.33333333,  -2.5       ,  -1.66666667,  -0.83333333,
         0.        ,   0.83333333,   1.66666667,   2.5       ,
         3.33333333,   4.16666667,   5.        ,   5.83333333,
         6.66666667,   7.5       ,   8.33333333,   9.16666667,
        10.        ])

In [11]:
# we need 24 steps -> range 25 
# between -10 and 10
# but clearly np.linspace() is more elegant and faster code to write
# you also need to convert to a numpy array, as faster to computer element-wise using np
np.array([-10 + i*(10 - (-10))/24 for i in range(25)])

array([-10.        ,  -9.16666667,  -8.33333333,  -7.5       ,
        -6.66666667,  -5.83333333,  -5.        ,  -4.16666667,
        -3.33333333,  -2.5       ,  -1.66666667,  -0.83333333,
         0.        ,   0.83333333,   1.66666667,   2.5       ,
         3.33333333,   4.16666667,   5.        ,   5.83333333,
         6.66666667,   7.5       ,   8.33333333,   9.16666667,
        10.        ])

numpy is also faster, let's test it

In [12]:
nparray_1 = np.linspace(-10, 10, 501)
nparray_1

array([-10.  ,  -9.96,  -9.92,  -9.88,  -9.84,  -9.8 ,  -9.76,  -9.72,
        -9.68,  -9.64,  -9.6 ,  -9.56,  -9.52,  -9.48,  -9.44,  -9.4 ,
        -9.36,  -9.32,  -9.28,  -9.24,  -9.2 ,  -9.16,  -9.12,  -9.08,
        -9.04,  -9.  ,  -8.96,  -8.92,  -8.88,  -8.84,  -8.8 ,  -8.76,
        -8.72,  -8.68,  -8.64,  -8.6 ,  -8.56,  -8.52,  -8.48,  -8.44,
        -8.4 ,  -8.36,  -8.32,  -8.28,  -8.24,  -8.2 ,  -8.16,  -8.12,
        -8.08,  -8.04,  -8.  ,  -7.96,  -7.92,  -7.88,  -7.84,  -7.8 ,
        -7.76,  -7.72,  -7.68,  -7.64,  -7.6 ,  -7.56,  -7.52,  -7.48,
        -7.44,  -7.4 ,  -7.36,  -7.32,  -7.28,  -7.24,  -7.2 ,  -7.16,
        -7.12,  -7.08,  -7.04,  -7.  ,  -6.96,  -6.92,  -6.88,  -6.84,
        -6.8 ,  -6.76,  -6.72,  -6.68,  -6.64,  -6.6 ,  -6.56,  -6.52,
        -6.48,  -6.44,  -6.4 ,  -6.36,  -6.32,  -6.28,  -6.24,  -6.2 ,
        -6.16,  -6.12,  -6.08,  -6.04,  -6.  ,  -5.96,  -5.92,  -5.88,
        -5.84,  -5.8 ,  -5.76,  -5.72,  -5.68,  -5.64,  -5.6 ,  -5.56,
      

In [13]:
nparray_2 = np.array([-10 + i * (10 - (-10))/500 for i in range(501)])
nparray_2

array([-10.  ,  -9.96,  -9.92,  -9.88,  -9.84,  -9.8 ,  -9.76,  -9.72,
        -9.68,  -9.64,  -9.6 ,  -9.56,  -9.52,  -9.48,  -9.44,  -9.4 ,
        -9.36,  -9.32,  -9.28,  -9.24,  -9.2 ,  -9.16,  -9.12,  -9.08,
        -9.04,  -9.  ,  -8.96,  -8.92,  -8.88,  -8.84,  -8.8 ,  -8.76,
        -8.72,  -8.68,  -8.64,  -8.6 ,  -8.56,  -8.52,  -8.48,  -8.44,
        -8.4 ,  -8.36,  -8.32,  -8.28,  -8.24,  -8.2 ,  -8.16,  -8.12,
        -8.08,  -8.04,  -8.  ,  -7.96,  -7.92,  -7.88,  -7.84,  -7.8 ,
        -7.76,  -7.72,  -7.68,  -7.64,  -7.6 ,  -7.56,  -7.52,  -7.48,
        -7.44,  -7.4 ,  -7.36,  -7.32,  -7.28,  -7.24,  -7.2 ,  -7.16,
        -7.12,  -7.08,  -7.04,  -7.  ,  -6.96,  -6.92,  -6.88,  -6.84,
        -6.8 ,  -6.76,  -6.72,  -6.68,  -6.64,  -6.6 ,  -6.56,  -6.52,
        -6.48,  -6.44,  -6.4 ,  -6.36,  -6.32,  -6.28,  -6.24,  -6.2 ,
        -6.16,  -6.12,  -6.08,  -6.04,  -6.  ,  -5.96,  -5.92,  -5.88,
        -5.84,  -5.8 ,  -5.76,  -5.72,  -5.68,  -5.64,  -5.6 ,  -5.56,
      

In [14]:
def test_1():
    return np.linspace(-10, 10, 501)

def test_2():
    return np.array([-10 + i * (10 - (-10))/500 for i in range(501)])

In [15]:
test_1()

array([-10.  ,  -9.96,  -9.92,  -9.88,  -9.84,  -9.8 ,  -9.76,  -9.72,
        -9.68,  -9.64,  -9.6 ,  -9.56,  -9.52,  -9.48,  -9.44,  -9.4 ,
        -9.36,  -9.32,  -9.28,  -9.24,  -9.2 ,  -9.16,  -9.12,  -9.08,
        -9.04,  -9.  ,  -8.96,  -8.92,  -8.88,  -8.84,  -8.8 ,  -8.76,
        -8.72,  -8.68,  -8.64,  -8.6 ,  -8.56,  -8.52,  -8.48,  -8.44,
        -8.4 ,  -8.36,  -8.32,  -8.28,  -8.24,  -8.2 ,  -8.16,  -8.12,
        -8.08,  -8.04,  -8.  ,  -7.96,  -7.92,  -7.88,  -7.84,  -7.8 ,
        -7.76,  -7.72,  -7.68,  -7.64,  -7.6 ,  -7.56,  -7.52,  -7.48,
        -7.44,  -7.4 ,  -7.36,  -7.32,  -7.28,  -7.24,  -7.2 ,  -7.16,
        -7.12,  -7.08,  -7.04,  -7.  ,  -6.96,  -6.92,  -6.88,  -6.84,
        -6.8 ,  -6.76,  -6.72,  -6.68,  -6.64,  -6.6 ,  -6.56,  -6.52,
        -6.48,  -6.44,  -6.4 ,  -6.36,  -6.32,  -6.28,  -6.24,  -6.2 ,
        -6.16,  -6.12,  -6.08,  -6.04,  -6.  ,  -5.96,  -5.92,  -5.88,
        -5.84,  -5.8 ,  -5.76,  -5.72,  -5.68,  -5.64,  -5.6 ,  -5.56,
      

In [16]:
%timeit test_1()

41.2 µs ± 1.87 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%timeit test_2()

109 µs ± 7.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
# now check calculations element-wise on numpy array and list
nparray_value = np.linspace(-10, 10, 500)
list_value = [-10 + i * (10 - (-10))/499 for i in range(500)]
# ensure that they have the same values
list(nparray_value) == list_value
# it says False due to the significant number of digits is different, otherwise they are the same values

False

In [19]:
nparray_value 

array([-10.        ,  -9.95991984,  -9.91983968,  -9.87975952,
        -9.83967936,  -9.7995992 ,  -9.75951904,  -9.71943888,
        -9.67935872,  -9.63927856,  -9.5991984 ,  -9.55911824,
        -9.51903808,  -9.47895792,  -9.43887776,  -9.3987976 ,
        -9.35871743,  -9.31863727,  -9.27855711,  -9.23847695,
        -9.19839679,  -9.15831663,  -9.11823647,  -9.07815631,
        -9.03807615,  -8.99799599,  -8.95791583,  -8.91783567,
        -8.87775551,  -8.83767535,  -8.79759519,  -8.75751503,
        -8.71743487,  -8.67735471,  -8.63727455,  -8.59719439,
        -8.55711423,  -8.51703407,  -8.47695391,  -8.43687375,
        -8.39679359,  -8.35671343,  -8.31663327,  -8.27655311,
        -8.23647295,  -8.19639279,  -8.15631263,  -8.11623246,
        -8.0761523 ,  -8.03607214,  -7.99599198,  -7.95591182,
        -7.91583166,  -7.8757515 ,  -7.83567134,  -7.79559118,
        -7.75551102,  -7.71543086,  -7.6753507 ,  -7.63527054,
        -7.59519038,  -7.55511022,  -7.51503006,  -7.47

In [20]:
list_value

[-10.0,
 -9.959919839679358,
 -9.919839679358718,
 -9.879759519038076,
 -9.839679358717435,
 -9.799599198396793,
 -9.759519038076153,
 -9.719438877755511,
 -9.67935871743487,
 -9.639278557114228,
 -9.599198396793588,
 -9.559118236472946,
 -9.519038076152304,
 -9.478957915831664,
 -9.438877755511022,
 -9.39879759519038,
 -9.358717434869739,
 -9.318637274549099,
 -9.278557114228457,
 -9.238476953907815,
 -9.198396793587174,
 -9.158316633266534,
 -9.118236472945892,
 -9.07815631262525,
 -9.03807615230461,
 -8.997995991983968,
 -8.957915831663327,
 -8.917835671342685,
 -8.877755511022045,
 -8.837675350701403,
 -8.797595190380761,
 -8.75751503006012,
 -8.71743486973948,
 -8.677354709418838,
 -8.637274549098196,
 -8.597194388777556,
 -8.557114228456914,
 -8.517034068136272,
 -8.47695390781563,
 -8.43687374749499,
 -8.396793587174349,
 -8.356713426853707,
 -8.316633266533067,
 -8.276553106212425,
 -8.236472945891784,
 -8.196392785571142,
 -8.1563126252505,
 -8.11623246492986,
 -8.076152304609

In [21]:
def test_1_operations():
    return (nparray_value + 2.5) **2

def test_2_operations():
    return [(value + 2.5)**2 for value in list_value]

In [22]:
list(test_1_operations())  == test_2_operations()

False

In [23]:
list(test_1_operations())

[56.25,
 55.650404014441705,
 55.054020867386086,
 54.4608505588331,
 53.87089308878277,
 53.284148457235105,
 52.700616664190115,
 52.12029770964776,
 51.54319159360805,
 50.96929831607101,
 50.39861787703664,
 49.831150276504914,
 49.26689551447584,
 48.705853590949445,
 48.14802450592568,
 47.593408259404576,
 47.04200485138613,
 46.493814281870364,
 45.94883655085723,
 45.40707165834675,
 44.86851960433895,
 44.33318038883379,
 43.801054011831276,
 43.272140473331426,
 42.74643977333425,
 42.22395191183971,
 41.704676888847835,
 41.188614704358606,
 40.67576535837206,
 40.16612885088815,
 39.659705181906894,
 39.1564943514283,
 38.656496359452376,
 38.15971120597909,
 37.666138891008465,
 37.175779414540514,
 36.6886327765752,
 36.20469897711254,
 35.723978016152536,
 35.24646989369521,
 34.772174609740524,
 34.30109216428849,
 33.83322255733914,
 33.36856578889242,
 32.90712185894836,
 32.44889076750695,
 31.993872514568224,
 31.542067100132133,
 31.093474524198697,
 30.6480947867

In [24]:
test_2_operations()

[56.25,
 55.650404014441705,
 55.054020867386086,
 54.4608505588331,
 53.87089308878277,
 53.284148457235105,
 52.700616664190115,
 52.12029770964776,
 51.54319159360805,
 50.96929831607101,
 50.39861787703664,
 49.831150276504914,
 49.26689551447584,
 48.705853590949445,
 48.14802450592568,
 47.593408259404576,
 47.04200485138613,
 46.493814281870364,
 45.94883655085723,
 45.40707165834675,
 44.86851960433893,
 44.33318038883379,
 43.801054011831276,
 43.272140473331426,
 42.74643977333425,
 42.22395191183971,
 41.704676888847835,
 41.188614704358606,
 40.67576535837206,
 40.16612885088815,
 39.659705181906894,
 39.1564943514283,
 38.656496359452376,
 38.15971120597909,
 37.666138891008465,
 37.175779414540514,
 36.6886327765752,
 36.20469897711254,
 35.723978016152536,
 35.24646989369521,
 34.772174609740524,
 34.30109216428849,
 33.83322255733914,
 33.36856578889242,
 32.90712185894836,
 32.44889076750695,
 31.993872514568203,
 31.542067100132133,
 31.093474524198697,
 30.6480947867

In [25]:
%timeit test_1_operations()

2.82 µs ± 40.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%timeit test_2_operations()

74.1 µs ± 13.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


So more than 20 times slower by using an operarations on list

# np.arange is the equivalent of Python's range

It is half open, so the last value is not included.

While Python's range works only on integers, np.arrange is more general, also with floats

In [27]:
list(range(2, 30, 2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [28]:
np.arange(2, 30, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
# can use floats with np.arange
np.arange(0.2, 12.2, 1)

array([ 0.2,  1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2,
       11.2])

In [30]:
# last element is the largest number in the series that is smaller than the second arguemnt

np.arange(0.2, 12.3, 2.2)

array([ 0.2,  2.4,  4.6,  6.8,  9. , 11.2])

In [31]:
# but better to use linear space for float step size
np.linspace(0.2, 11.2, 6)

array([ 0.2,  2.4,  4.6,  6.8,  9. , 11.2])

# When to use each

* use np.linspace() when you have the fixed start and end
* use np.arange() when you have a fixed step size

In [32]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [33]:
# more readable
np.linspace(start = -5, stop = 5, num = 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [34]:
# change the data type
np.linspace(-10, 10, 21)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [35]:
nparray = np.linspace(-10, 10, 21, dtype = int)
nparray

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [36]:
type(nparray[0])

numpy.int64

In [37]:
nparray = np.linspace(-10, 10, 21, dtype = np.int8)
nparray

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10], dtype=int8)

In [38]:
type(nparray[0])

numpy.int8

In [39]:
# but be careful, it rounds the values and can no longer be a linear space sometimes
np.linspace(-5, 5, 20)

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [40]:
np.linspace(-5, 5, 20, dtype = np.int8)

array([-5, -4, -3, -3, -2, -2, -1, -1,  0,  0,  0,  0,  1,  1,  2,  2,  3,
        3,  4,  5], dtype=int8)

In [41]:
# by default it is a closed interval, but you can make it half open
np.linspace(-10, 10, 21)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [42]:
np.linspace(-10, 10, 21, endpoint = False)

array([-10.        ,  -9.04761905,  -8.0952381 ,  -7.14285714,
        -6.19047619,  -5.23809524,  -4.28571429,  -3.33333333,
        -2.38095238,  -1.42857143,  -0.47619048,   0.47619048,
         1.42857143,   2.38095238,   3.33333333,   4.28571429,
         5.23809524,   6.19047619,   7.14285714,   8.0952381 ,
         9.04761905])

In [43]:
np.linspace(-10, 10, 20, endpoint = False)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.])

In [44]:
# it also returns the step that it calculates, add retstep = True
nparray, step_size = np.linspace(-10, 10, 20, endpoint = False, retstep = True)
step_size

1.0

In [45]:
# higher dimensionality array, like 2D
nparray = np.linspace(start = [2, 5, 9], stop= [100, 130, 160], num = 10)
nparray

array([[  2.        ,   5.        ,   9.        ],
       [ 12.88888889,  18.88888889,  25.77777778],
       [ 23.77777778,  32.77777778,  42.55555556],
       [ 34.66666667,  46.66666667,  59.33333333],
       [ 45.55555556,  60.55555556,  76.11111111],
       [ 56.44444444,  74.44444444,  92.88888889],
       [ 67.33333333,  88.33333333, 109.66666667],
       [ 78.22222222, 102.22222222, 126.44444444],
       [ 89.11111111, 116.11111111, 143.22222222],
       [100.        , 130.        , 160.        ]])

In [46]:
nparray.shape

(10, 3)

In [47]:
# to create the transpose of this array, set axis = 1
nparray = np.linspace(start = [2, 5, 9], 
                      stop= [100, 130, 160], 
                      num = 10,
                      axis = 1)
nparray 

array([[  2.        ,  12.88888889,  23.77777778,  34.66666667,
         45.55555556,  56.44444444,  67.33333333,  78.22222222,
         89.11111111, 100.        ],
       [  5.        ,  18.88888889,  32.77777778,  46.66666667,
         60.55555556,  74.44444444,  88.33333333, 102.22222222,
        116.11111111, 130.        ],
       [  9.        ,  25.77777778,  42.55555556,  59.33333333,
         76.11111111,  92.88888889, 109.66666667, 126.44444444,
        143.22222222, 160.        ]])

In [48]:
# to summarize, the default values are
np.linspace(1.1,
         2.3,
         num=50,
         endpoint=True,
         retstep=False,
         dtype=None,
         axis=0
         )

array([1.1       , 1.1244898 , 1.14897959, 1.17346939, 1.19795918,
       1.22244898, 1.24693878, 1.27142857, 1.29591837, 1.32040816,
       1.34489796, 1.36938776, 1.39387755, 1.41836735, 1.44285714,
       1.46734694, 1.49183673, 1.51632653, 1.54081633, 1.56530612,
       1.58979592, 1.61428571, 1.63877551, 1.66326531, 1.6877551 ,
       1.7122449 , 1.73673469, 1.76122449, 1.78571429, 1.81020408,
       1.83469388, 1.85918367, 1.88367347, 1.90816327, 1.93265306,
       1.95714286, 1.98163265, 2.00612245, 2.03061224, 2.05510204,
       2.07959184, 2.10408163, 2.12857143, 2.15306122, 2.17755102,
       2.20204082, 2.22653061, 2.25102041, 2.2755102 , 2.3       ])